version: "3.9"
services:
    db:
      image: patricechaula/ejs-django-db
      volumes:
        - data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: initial123
        MYSQL_DATABASE: ejs
        MYSQL_USER: sa
        MYSQL_PASSWORD: initial123
    web:
      image: patricechaula/ejs-django-frontend
      command: gunicorn --bind 0.0.0.0:8000 mysite4.wsgi
      ports:
        - "8000:8000"
      depends_on:
        - db
volumes:
    data: